server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/thesismanage?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "000001"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl:
  global-config:
    db-config:
      id-type: ASSIGN_ID
upload:
  path: D:\Workspace\SpringBoot\thesis-management-system\src\main\resources\upload
#  relative-path: upload/